site_name: PHT Documentation & User Guide
theme:
  name: material
  features:
    - navigation.tracking
    - navigation.expand

site_dir: ./site

nav:
  - Home: index.md
  - User Guide:
    - User Interface: user_interface.md
    - Creating Trains: trains.md
    - Offline Tool: offline_tool.md
    - Station: station.md

markdown_extensions:
  - admonition