site_name: PHT Documentation & User Guide
theme:
  name: material
  features:
    - navigation.tracking
    - navigation.expand

  palette:
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode

site_dir: public

nav:
  - What is the PHT?: index.md
  - Components: components.md
  - Guide (Analyst):
    - User Interface: user_guide/user_interface.md
    - Desktop App (Offline Tool): user_guide/desktop_app.md
    - Trains: user_guide/trains.md
    - FHIR Query: user_guide/fhir_query.md
  - Guide (Station Administrator):
    - Central UI: station_guide/central_ui.md
    - Installation: station_guide/installation.md
    - Station: station_guide/station.md

  #- CORD Demo:
    #- Overview: cord_demo/cord_demo.md
    #- FHIR Query: cord_demo/cord_fhir.md
    #- R Code: cord_demo/cord_r.md
    #- Python Code: cord_demo/cord_python.md
  - Glossar: glossar.md
  - For Your Information (FYI): fyi.md


markdown_extensions:
  - admonition
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

plugins:
  - mkdocstrings
  - search