site_name: PHT Documentation & User Guide
theme:
  name: material
  features:
    - navigation.tracking
    - navigation.expand

site_dir: public

nav:
  - Home: index.md
  - Concepts: concepts.md
  - User Guide:
    - User Interface: user_interface.md
    - Offline Tool: offline_tool.md
    - Station: station.md
    - Trains: trains.md
  - CORD Demo:
    - Overview: cord_demo.md
    - FHIR Query: cord_fhir.md
    - R Code: cord_r.md
    - Python Code: cord_python.md


markdown_extensions:
  - admonition
  - pymdownx.highlight
  - pymdownx.superfences

plugins:
  - mkdocstrings
  - search